export const copy = {
  appName: 'SnapCut',
  projects: {
    newAction: 'New Project',
    diagnosticsAction: 'Diagnostics',
    emptyTitle: 'No projects yet',
    emptyMessage: 'Create a project to start arranging clips from your local media.',
    loadError: 'Your projects could not be loaded.',
    createError: 'The project could not be created.',
    renameError: 'The project could not be renamed.',
    deleteError: 'The project could not be deleted.',
    unknownError: 'Something went wrong. Try again.',
    loading: 'Loading projects…',
    retry: 'Try Again',
    openHint: 'Opens the project editor',
    renameAction: 'Rename',
    deleteAction: 'Delete',
    sourceCount: (count: number) => `${count} ${count === 1 ? 'source' : 'sources'}`,
    clipCount: (count: number) => `${count} ${count === 1 ? 'clip' : 'clips'}`,
    duration: (value: string) => `${value} total`,
    updated: (value: string) => `Updated ${value}`,
    repairTitle: 'Needs repair',
    repairIssue: (issue: string) => {
      const messages: Record<string, string> = {
        PROJECT_METADATA_CORRUPT: 'Project metadata is damaged.',
        SOURCE_DIRECTORY_MISSING: 'A private source folder is missing.',
        SOURCE_METADATA_INVALID: 'Private source metadata is damaged.',
        SOURCE_RELATION_MISMATCH: 'A source no longer matches this project.',
        PRIVATE_MEDIA_MISSING_OR_EMPTY: 'A private audio file is missing or empty.',
        PRIVATE_MEDIA_SIZE_MISMATCH: 'A private audio file changed unexpectedly.',
        PRIVATE_MEDIA_HASH_UNVERIFIED: 'A private audio file has not been verified.',
        WAVEFORM_MISSING: 'A completed waveform file is missing.',
        WAVEFORM_INVALID: 'Waveform data is damaged.',
        WAVEFORM_DURATION_MISMATCH: 'Waveform duration does not match its source.',
        INCOMPLETE_IMPORT_TRANSACTION: 'An import transaction did not finish cleanly.',
      };
      return messages[issue] ?? 'Project data needs attention.';
    },
    corruptTitle: 'Damaged project',
    corruptMessage:
      'SnapCut preserved this project directory, but its metadata cannot be opened. You can safely delete it.',
    corruptDeleteHint: 'Deletes only this damaged project directory from SnapCut',
  },
  nameDialog: {
    renameTitle: 'Rename Project',
    saveAction: 'Save',
    cancelAction: 'Cancel',
    fieldLabel: 'Project name',
    placeholder: 'My audio edit',
    requiredError: 'Enter a project name.',
    tooLongError: 'Use 80 characters or fewer.',
  },
  deleteDialog: {
    title: 'Delete project?',
    message: (name: string) => `“${name}” and its private media will be removed from SnapCut.`,
    warning: 'This cannot be undone.',
    cancelAction: 'Keep Project',
    confirmAction: 'Delete Project',
  },
  editor: {
    loading: 'Loading project…',
    notFoundTitle: 'Project unavailable',
    notFoundMessage: 'This project may have been deleted or needs repair.',
    backAction: 'Back to projects',
    addMediaAction: 'Add Media',
    addMediaUnavailableHint: 'Opens the Android document picker for one local audio or video file',
    mediaTitle: 'Media',
    mediaSubtitle: 'Add full media to the end of Track 1',
    mediaImportAction: 'Import Audio or Video',
    mediaEmptyTitle: 'No media yet',
    mediaEmptyMessage: 'Import local audio or extract a soundtrack from a video.',
    mediaCloseAction: 'Close media library',
    mediaPreviewAction: (name: string) => `Preview ${name}`,
    mediaPreviewLoading: (name: string) => `Loading ${name} preview`,
    mediaPauseAction: (name: string) => `Pause ${name}`,
    mediaAddAction: (name: string) => `Add ${name} to Track 1`,
    sourcesTitle: 'Sources',
    sourceSelectorLabel: 'Project sources',
    selectedSource: 'Selected source',
    waveformPending: 'Waveform will appear here after this source is ready.',
    waveformUnavailable: 'Waveform data is not available yet.',
    waveformLabel: 'Source waveform and selected range',
    waveformLoading: 'Loading waveform…',
    retryWaveform: 'Retry waveform',
    resumeWaveform: 'Resume waveform',
    cancelWaveform: 'Cancel waveform',
    waveformQueued: 'Waveform is waiting for the current media task.',
    waveformWriting: 'Saving waveform…',
    waveformCancelling: 'Stopping waveform…',
    waveformPaused: 'Waveform processing is paused. Resume it when you are ready.',
    waveformFailed: 'Waveform generation failed. The source audio is still available.',
    waveformProgress: (percent: number | null) =>
      percent === null ? 'Building waveform…' : `Building waveform… ${percent}%`,
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    panEarlier: 'Pan earlier',
    panLater: 'Pan later',
    zoomLevel: (value: number) => `${value}×`,
    sourceDurationLabel: 'Duration',
    sourceCodecLabel: 'Codec',
    sourceSampleRateLabel: 'Sample rate',
    sourceChannelsLabel: 'Channels',
    sampleRate: (value: number) => `${value.toLocaleString('en-US')} Hz`,
    channels: (value: number) => (value === 1 ? 'Mono' : 'Stereo'),
    selectionTitle: 'Clip range',
    selectionStartLabel: 'Start (ms)',
    selectionEndLabel: 'End (ms)',
    selectionDurationLabel: 'Selected duration',
    selectionPlayAction: 'Play Selection',
    selectionPauseAction: 'Pause Selection',
    selectionPreviewUnavailable: 'Selection preview is waiting for the native player.',
    addClipAction: 'Add Clip',
    saveClipAction: 'Save Clip',
    cancelEditAction: 'Cancel Edit',
    invalidTimeError: 'Enter a whole number of milliseconds.',
    invalidRangeError: 'Choose a range of at least 100 ms within the source.',
    saveError: 'The project changes could not be saved.',
    sourcesEmptyTitle: 'Add your first source',
    sourcesEmptyMessage:
      'Choose local audio or video to begin. SnapCut keeps the editable audio private to this app.',
    compositionTitle: 'Composition',
    compositionSummary: (count: number, duration: string) =>
      `${count} ${count === 1 ? 'clip' : 'clips'} · ${duration}`,
    clipsEmptyTitle: 'No clips yet',
    clipsEmptyMessage: 'After adding media, select a range and add it to your composition.',
    compositionPlayAction: 'Play Composition',
    compositionPauseAction: 'Pause Composition',
    undoAction: 'Undo',
    redoAction: 'Redo',
    compositionPreviewUnavailable: 'Composition preview is waiting for the native player.',
    previewLoading: 'Loading Preview…',
    previewError: 'Preview could not be played.',
    seekBackward: 'Back 5 seconds',
    seekForward: 'Forward 5 seconds',
    playbackPosition: (position: string, duration: string) => `${position} / ${duration}`,
    exportAction: 'Export',
    exportDisabledHint: 'Add at least one clip before exporting',
    exportUnavailableHint: 'Export is unavailable until the native codecs are ready',
    exportHint: 'Checks available formats and opens export options',
  },
  clips: {
    unknownSource: 'Unknown source',
    range: (start: string, end: string) => `${start} – ${end}`,
    duration: (value: string) => `${value} clip`,
    moveEarlier: 'Move earlier',
    moveLater: 'Move later',
    edit: 'Edit',
    duplicate: 'Duplicate',
    delete: 'Delete',
  },
  export: {
    title: 'Export Audio',
    preflighting: 'Checking export options…',
    nameLabel: 'File name',
    namePlaceholder: 'My SnapCut export',
    invalidName: 'Enter a safe file name without an extension.',
    formatLabel: 'Format',
    compositionDuration: (value: string) => `Composition duration: ${value}`,
    estimatedSize: (value: string) => `Estimated size: ${value}`,
    sampleRate: (value: number) => `${value.toLocaleString('en-US')} Hz`,
    channels: (value: number) => (value === 1 ? 'Mono' : 'Stereo'),
    m4a: 'M4A · No re-encoding',
    m4aReencoded: 'M4A · Re-encoded AAC',
    flac: 'FLAC · Lossless',
    mp3: 'MP3 · 320 kbps',
    m4aBoundaryAdjustment: (milliseconds: number) =>
      `M4A copies AAC without re-encoding. Cut points will be adjusted by at most ${milliseconds} ms to match AAC frame boundaries.`,
    flacSourceCaveat:
      'FLAC preserves the exported PCM, but cannot restore detail already removed from AAC or MP3 sources.',
    mixClippingWarning:
      'Overlapping tracks may clip. SnapCut hard-limits samples that exceed the valid audio range.',
    unavailableReason: 'Unavailable',
    startAction: 'Export',
    cancelAction: 'Cancel',
    closeAction: 'Close',
    shareAction: 'Share',
    retryAction: 'Try Again',
    cancelling: 'Stopping export…',
    exporting: (stage: string, percent: number | null) =>
      percent === null ? stage : `${stage} · ${percent}%`,
    successTitle: 'Export complete',
    successMessage: (name: string) => `${name} is ready in Music/SnapCut.`,
    successDuration: (value: string) => `Actual duration: ${value}`,
    successBoundaryAdjustment: (milliseconds: number) =>
      `Maximum M4A boundary adjustment: ${milliseconds} ms`,
    preflightError: 'SnapCut could not prepare export options.',
    exportError: 'SnapCut could not finish this export.',
    cancelled: 'Export cancelled.',
    shareError: 'SnapCut could not open the Android share sheet.',
  },
  import: {
    title: 'Add Media',
    picking: 'Choose one local audio or video file…',
    inspecting: 'Checking media…',
    extracting_or_copying: 'Creating private audio…',
    verifying: 'Verifying private audio…',
    committing: 'Saving source…',
    scheduling_waveform: 'Scheduling waveform…',
    canceling: 'Stopping import…',
    complete: 'Source added.',
    cancelled: 'Import cancelled.',
    cancelAction: 'Cancel',
    closeAction: 'Close',
    retryAction: 'Choose Again',
    progress: (stage: string, percent: number | null) =>
      percent === null ? stage : `${stage} · ${percent}%`,
  },
  diagnostics: {
    title: 'Development Diagnostics',
    backAction: 'Back',
    refreshAction: 'Refresh',
    shareAction: 'Share Log',
    clearAction: 'Clear Log',
    unavailableTitle: 'Diagnostics unavailable',
    unavailableMessage: 'This screen is included only in development builds.',
    moduleTitle: 'Native Module',
    activityTitle: 'Activity',
    logTitle: 'Bounded Local Log',
    noEntries: 'No diagnostic entries.',
  },
  common: {
    dismissError: 'Dismiss error',
  },
} as const;
